apiVersion: hops.ops.com.ai/v1alpha1
kind: XIRSA
metadata:
  name: example-irsa
spec:
  clusterName: cluster-x
  deletionPolicy: Orphan
  aws:
    providerConfig: legacy-fallback
  awsProviderConfig: shared-aws
  accountId: "123456789012"
  name: "loki"
  oidc: "https://oidc.eks.us-west-2.amazonaws.com/id/EXAMPLE1234567890"
  permissionsBoundary: "arn:aws:iam::123456789012:policy/eks-boundary"
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "LokiStorage",
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:PutObject",
            "s3:GetObject",
            "s3:DeleteObject"
          ],
          "Resource": [
            "arn:aws:s3:::example-loki-chunks",
            "arn:aws:s3:::example-loki-chunks/*",
            "arn:aws:s3:::example-loki-ruler",
            "arn:aws:s3:::example-loki-ruler/*"
          ]
        }
      ]
    }
  rolePrefix: "irsa-"
  policyPrefix: "irsa-"
  tags:
    team: platform
    service: logging
  serviceAccount:
    namespace: "loki"
    name: "loki"
