apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: irsas.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: IRSA
    plural: irsas
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              accountId:
                type: string
              aws:
                properties:
                  providerConfig:
                    type: string
                type: object
              clusterName:
                type: string
              managementPolicies:
                description: ManagementPolicies for AWS resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use ["Create", "Observe", "Update", "LateInitialize"].
                type: array
                items:
                  type: string
                  enum:
                    - "*"
                    - Create
                    - Observe
                    - Update
                    - Delete
                    - LateInitialize
                default: ["*"]
              name:
                type: string
              oidc:
                type: string
              permissionsBoundary:
                type: string
              policy:
                type: string
              policyPrefix:
                type: string
              rolePrefix:
                type: string
              serviceAccount:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
              tags:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required:
            - accountId
            - name
            - oidc
            - policy
            - serviceAccount
            - managementPolicies
            type: object
          status:
            type: object
        required:
        - spec
        type: object
    served: true
